version: '3.4'
services:
  php:
    image: thecodingmachine/php:8.1-v4-cli-node14
    command: 'php -S 0.0.0.0:8080 -t /app/public'
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      PHP_EXTENSIONS: xdebug
    ports:
      - 8080:8080
